# Generated by Django 5.2 on 2025-04-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lcwaikiki', '0006_update_store_foreign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this configuration', max_length=100)),
                ('seller_id', models.CharField(help_text='Trendyol Seller ID', max_length=100)),
                ('api_key', models.CharField(help_text='Trendyol API Key', max_length=255)),
                ('api_secret', models.CharField(help_text='Trendyol API Secret', max_length=255)),
                ('base_url', models.URLField(default='https://api.trendyol.com/sapigw', help_text='Trendyol API base URL')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol API Configuration',
                'verbose_name_plural': 'Trendyol API Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField(help_text='Trendyol Brand ID', unique=True)),
                ('name', models.CharField(help_text='Brand Name', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol Brand',
                'verbose_name_plural': 'Trendyol Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(help_text='Trendyol Category ID', unique=True)),
                ('name', models.CharField(help_text='Category Name', max_length=255)),
                ('parent_id', models.IntegerField(blank=True, help_text='Parent Category ID', null=True)),
                ('path', models.CharField(blank=True, help_text='Full category path', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol Category',
                'verbose_name_plural': 'Trendyol Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrendyolProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('product_main_id', models.CharField(blank=True, help_text='Main product ID', max_length=100)),
                ('stock_code', models.CharField(blank=True, help_text='Stock code', max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField(default=0)),
                ('vat_rate', models.IntegerField(default=18, help_text='VAT rate percentage')),
                ('currency_type', models.CharField(choices=[('TRY', 'Turkish Lira'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='TRY', max_length=3)),
                ('image_url', models.URLField(blank=True)),
                ('additional_images', models.JSONField(blank=True, default=list)),
                ('trendyol_id', models.CharField(blank=True, help_text='Trendyol product ID', max_length=50)),
                ('trendyol_url', models.URLField(blank=True, help_text='URL to the product on Trendyol')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Product attributes for Trendyol')),
                ('batch_id', models.CharField(blank=True, help_text='Batch ID for synchronization', max_length=100)),
                ('batch_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the synchronization', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Status or error message')),
                ('last_check_time', models.DateTimeField(blank=True, help_text='Last status check time', null=True)),
                ('last_sync_time', models.DateTimeField(blank=True, help_text='Last successful sync time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lcwaikiki_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trendyol_products', to='lcwaikiki.product')),
            ],
            options={
                'verbose_name': 'Trendyol Product',
                'verbose_name_plural': 'Trendyol Products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['barcode'], name='trendyol_tr_barcode_94fba8_idx'), models.Index(fields=['product_main_id'], name='trendyol_tr_product_fddd57_idx'), models.Index(fields=['batch_status'], name='trendyol_tr_batch_s_f1f3da_idx'), models.Index(fields=['last_sync_time'], name='trendyol_tr_last_sy_72999e_idx')],
            },
        ),
    ]
