# Generated by Django 5.2 on 2025-04-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://apigw.trendyol.com/integration', help_text='Trendyol API base URL'),
        ),
    ]
