# Generated by Django 5.2 on 2025-04-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0002_alter_trendyolapiconfig_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolproduct',
            name='pim_category_id',
            field=models.IntegerField(blank=True, help_text='Product Information Management Category ID (optional)', null=True),
        ),
    ]
