# Generated by Django 5.2 on 2025-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0004_trendyolapiconfig_supplier_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://api.trendyol.com/sapigw', help_text='Trendyol API base URL'),
        ),
    ]
