# Generated by Django 5.2 on 2025-04-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0005_alter_trendyolapiconfig_base_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://api.trendyol.com/sapigw', help_text="Trendyol API base URL - should be 'https://api.trendyol.com/sapigw'"),
        ),
    ]
