# Generated by Django 5.2 on 2025-04-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0006_alter_trendyolapiconfig_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolAttribute',
            fields=[
                ('attribute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('variant', models.BooleanField(default=False)),
                ('attribute_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol Attribute',
                'verbose_name_plural': 'Trendyol Attributes',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://apigw.trendyol.com', help_text="Trendyol API base URL - should be 'https://apigw.trendyol.com'"),
        ),
        migrations.CreateModel(
            name='TrendyolAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='trendyol.trendyolattribute')),
            ],
            options={
                'verbose_name': 'Trendyol Attribute Value',
                'verbose_name_plural': 'Trendyol Attribute Values',
                'ordering': ['name'],
                'unique_together': {('attribute', 'value_id')},
            },
        ),
    ]
