# Generated by Django 5.2 on 2025-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0006_alter_trendyolapiconfig_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolproduct',
            name='variant_key',
            field=models.CharField(blank=True, help_text='Variant key (e.g. size name)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://apigw.trendyol.com', help_text="Trendyol API base URL - should be 'https://apigw.trendyol.com'"),
        ),
    ]
