# Generated by Django 5.2 on 2025-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol', '0006_alter_trendyolapiconfig_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolBatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(help_text='Batch ID from Trendyol', max_length=100, unique=True)),
                ('request_type', models.CharField(choices=[('create', 'Create Products'), ('update', 'Update Products'), ('price_inventory', 'Update Price and Inventory'), ('delete', 'Delete Products')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='Data sent in the request')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='Response data from Trendyol')),
                ('item_count', models.IntegerField(default=0, help_text='Number of items in the batch')),
                ('success_count', models.IntegerField(default=0, help_text='Number of successful items')),
                ('failed_count', models.IntegerField(default=0, help_text='Number of failed items')),
                ('error_message', models.TextField(blank=True, help_text='Error message if batch failed')),
                ('last_check_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol Batch Request',
                'verbose_name_plural': 'Trendyol Batch Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://apigw.trendyol.com', help_text="Trendyol API base URL - should be 'https://apigw.trendyol.com'"),
        ),
    ]
