# Generated by Django 5.2 on 2025-04-14 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0006_update_store_foreign_key'),
        ('trendyol', '0006_alter_trendyolapiconfig_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolBatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True, verbose_name='Batch ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='waiting', max_length=50, verbose_name='Status')),
                ('status_message', models.TextField(blank=True, verbose_name='Status Message')),
                ('operation_type', models.CharField(max_length=100, verbose_name='Operation Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Last Checked At')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Items Count')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Success Count')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='Fail Count')),
                ('response_data', models.TextField(blank=True, null=True, verbose_name='Response Data')),
            ],
            options={
                'verbose_name': 'Trendyol Batch Request',
                'verbose_name_plural': 'Trendyol Batch Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='trendyolapiconfig',
            options={'ordering': ['-is_active', '-updated_at'], 'verbose_name': 'Trendyol API Configuration', 'verbose_name_plural': 'Trendyol API Configurations'},
        ),
        migrations.RemoveIndex(
            model_name='trendyolproduct',
            name='trendyol_tr_last_sy_72999e_idx',
        ),
        migrations.RemoveField(
            model_name='trendyolapiconfig',
            name='supplier_id',
        ),
        migrations.RemoveField(
            model_name='trendyolapiconfig',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='trendyolproduct',
            name='last_check_time',
        ),
        migrations.RemoveField(
            model_name='trendyolproduct',
            name='last_sync_time',
        ),
        migrations.RemoveField(
            model_name='trendyolproduct',
            name='trendyol_url',
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='cargo_company_id',
            field=models.PositiveIntegerField(default=10, verbose_name='Cargo Company ID'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='dimensional_weight',
            field=models.PositiveIntegerField(default=1, verbose_name='Dimensional Weight'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sale Price'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='api_key',
            field=models.CharField(max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='api_secret',
            field=models.CharField(max_length=255, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='base_url',
            field=models.URLField(default='https://apigw.trendyol.com/integration/', verbose_name='API Base URL'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Configuration Name'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='seller_id',
            field=models.CharField(max_length=100, verbose_name='Seller ID'),
        ),
        migrations.AlterField(
            model_name='trendyolapiconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='trendyolbrand',
            name='brand_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Brand ID'),
        ),
        migrations.AlterField(
            model_name='trendyolbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='trendyolbrand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='trendyolbrand',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='trendyolbrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='category_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent ID'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='path',
            field=models.TextField(blank=True, verbose_name='Category Path'),
        ),
        migrations.AlterField(
            model_name='trendyolcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Additional Images'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='attributes',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Attributes'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='barcode',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='batch_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch ID'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='batch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='pending', max_length=50, verbose_name='Batch Status'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='brand_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Brand ID'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='category_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Category ID'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='currency_type',
            field=models.CharField(default='TRY', max_length=10, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Main Image URL'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='lcwaikiki_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trendyol_products', to='lcwaikiki.product', verbose_name='LC Waikiki Product'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='pim_category_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='PIM Category ID'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='product_main_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Product Main ID'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='status_message',
            field=models.TextField(blank=True, verbose_name='Status Message'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='stock_code',
            field=models.CharField(max_length=100, verbose_name='Stock Code'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='trendyol_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trendyol Product ID'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='trendyolproduct',
            name='vat_rate',
            field=models.PositiveIntegerField(default=18, verbose_name='VAT Rate'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='batch_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='trendyol.trendyolbatchrequest', verbose_name='Batch Request'),
        ),
    ]
