[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django-unfold>=0.54.0",
    "django>=5.2",
    "djangorestframework>=3.16.0",
]
