# Generated by Django 5.2 on 2025-04-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendyolAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=100, verbose_name='Satıcı ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key')),
                ('base_url', models.CharField(default='https://apigw.trendyol.com/integration/', max_length=255, verbose_name='API Base URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol API Konfigürasyonu',
                'verbose_name_plural': 'Trendyol API Konfigürasyonları',
            },
        ),
        migrations.CreateModel(
            name='TrendyolProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barkod')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('product_main_id', models.CharField(max_length=100, unique=True, verbose_name='Ürün Ana ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Marka Adı')),
                ('category_name', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stok Miktarı')),
                ('stock_code', models.CharField(max_length=100, verbose_name='Stok Kodu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Liste Fiyatı')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Satış Fiyatı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image_url', models.URLField(verbose_name='Resim URL')),
                ('vat_rate', models.PositiveSmallIntegerField(default=10, verbose_name='KDV Oranı')),
                ('currency_type', models.CharField(default='TRY', max_length=10, verbose_name='Para Birimi')),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch ID')),
                ('batch_status', models.CharField(choices=[('pending', 'Beklemede'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Batch Durumu')),
                ('status_message', models.TextField(blank=True, null=True, verbose_name='Durum Mesajı')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='Son Kontrol Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trendyol Ürünü',
                'verbose_name_plural': 'Trendyol Ürünleri',
            },
        ),
    ]
