# Generated by Django 5.2 on 2025-04-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trendyol_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='api_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='API Secret'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='batch_status_endpoint',
            field=models.CharField(default='suppliers/{supplierId}/products/batch-requests/{batchId}', max_length=255, verbose_name='Batch Durum Endpoint'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='brands_endpoint',
            field=models.CharField(default='brands', max_length=255, verbose_name='Markalar Endpoint'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='categories_endpoint',
            field=models.CharField(default='product-categories', max_length=255, verbose_name='Kategoriler Endpoint'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='category_attributes_endpoint',
            field=models.CharField(default='product-categories/{categoryId}/attributes', max_length=255, verbose_name='Kategori Özellikleri Endpoint'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='product_detail_endpoint',
            field=models.CharField(default='product/sellers/{sellerId}/products', max_length=255, verbose_name='Ürün Detay Endpoint'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='products_endpoint',
            field=models.CharField(default='product/sellers/{sellerId}/products', max_length=255, verbose_name='Ürünler Endpoint'),
        ),
        migrations.AddField(
            model_name='trendyolapiconfig',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tedarikçi ID'),
        ),
    ]
