# Generated by Django 5.2 on 2025-04-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0006_update_store_foreign_key'),
        ('trendyol_app', '0003_alter_trendyolapiconfig_batch_status_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendyolproduct',
            name='brand_id',
            field=models.IntegerField(default=102, verbose_name='Marka ID'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kategori ID'),
        ),
        migrations.AddField(
            model_name='trendyolproduct',
            name='lcwaikiki_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trendyol_products', to='lcwaikiki.product', verbose_name='LCWaikiki Ürünü'),
        ),
    ]
