# Generated by Django 5.2 on 2025-04-10 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0002_productavailableurl_productdeletedurl_productnewurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityConfiguration',
            fields=[
                ('city_id', models.CharField(choices=[('866', 'Adana'), ('894', 'Adıyaman'), ('882', 'Afyon'), ('927', 'Ağrı'), ('920', 'Aksaray'), ('935', 'Amasya'), ('873', 'Ankara'), ('867', 'Antalya'), ('948', 'Ardahan'), ('905', 'Artvin'), ('871', 'Aydın'), ('885', 'Balıkesir'), ('939', 'Bartın'), ('925', 'Batman'), ('936', 'Bayburt'), ('917', 'Bilecik'), ('941', 'Bingöl'), ('897', 'Bitlis'), ('923', 'Bolu'), ('919', 'Burdur'), ('868', 'Bursa'), ('910', 'Çanakkale'), ('929', 'Çankırı'), ('888', 'Çorum'), ('874', 'Denizli'), ('926', 'Diyarbakır'), ('947', 'Düzce'), ('906', 'Edirne'), ('913', 'Elazığ'), ('922', 'Erzincan'), ('900', 'Erzurum'), ('887', 'Eskişehir'), ('890', 'Gaziantep'), ('884', 'Giresun'), ('943', 'Gümüşhane'), ('924', 'Hakkari'), ('877', 'Hatay'), ('914', 'Iğdır'), ('908', 'Isparta'), ('865', 'İstanbul'), ('872', 'İzmir'), ('898', 'Kahramanmaraş'), ('912', 'Karabük'), ('883', 'Karaman'), ('915', 'Kars'), ('895', 'Kastamonu'), ('869', 'Kayseri'), ('896', 'Kırıkkale'), ('902', 'Kırklareli'), ('940', 'Kırşehir'), ('876', 'Kocaeli'), ('875', 'Konya'), ('901', 'Kütahya'), ('893', 'Malatya'), ('891', 'Manisa'), ('930', 'Mardin'), ('903', 'Mersin'), ('899', 'Muğla'), ('932', 'Muş'), ('907', 'Nevşehir'), ('911', 'Niğde'), ('904', 'Ordu'), ('892', 'Osmaniye'), ('928', 'Rize'), ('870', 'Sakarya'), ('916', 'Samsun'), ('931', 'Siirt'), ('918', 'Sinop'), ('879', 'Sivas'), ('921', 'Şanlıurfa'), ('942', 'Şırnak'), ('880', 'Tekirdağ'), ('909', 'Tokat'), ('878', 'Trabzon'), ('937', 'Tunceli'), ('886', 'Uşak'), ('933', 'Van'), ('889', 'Yalova'), ('938', 'Yozgat'), ('881', 'Zonguldak')], max_length=3, primary_key=True, serialize=False, verbose_name='City ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'City Configuration',
                'verbose_name_plural': 'City Configurations',
            },
        ),
        migrations.AddField(
            model_name='config',
            name='price_config',
            field=models.JSONField(default=dict, help_text='Price configuration in JSON format'),
        ),
        migrations.AddField(
            model_name='config',
            name='default_city',
            field=models.ForeignKey(blank=True, help_text='Default city for inventory checks', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lcwaikiki.cityconfiguration'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=35, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('images', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=50)),
                ('last_checking', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'indexes': [models.Index(fields=['status'], name='lcwaikiki_p_status_77c486_idx'), models.Index(fields=['last_checking'], name='lcwaikiki_p_last_ch_a0a67f_idx'), models.Index(fields=['product_code'], name='lcwaikiki_p_product_7c8f60_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('size_id', models.CharField(blank=True, max_length=50, null=True)),
                ('size_general_stock', models.IntegerField(default=0)),
                ('product_option_size_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode_list', models.JSONField(default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='lcwaikiki.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'unique_together': {('product', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('store_county', models.CharField(blank=True, max_length=100, null=True)),
                ('store_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='lcwaikiki.cityconfiguration')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='SizeStoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_stock', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='lcwaikiki.productsize')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='lcwaikiki.store')),
            ],
            options={
                'verbose_name': 'Size Store Stock',
                'verbose_name_plural': 'Size Store Stocks',
                'unique_together': {('product_size', 'store')},
            },
        ),
    ]
