# Generated by Django 5.2 on 2025-04-11 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0002_productavailableurl_productdeletedurl_productnewurl'),
    ]

    operations = [

        migrations.AddField(
            model_name='config',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this config is active'),
        ),
        migrations.AlterField(
            model_name='config',
            name='brands',
            field=models.JSONField(help_text='Brand and configuration data in JSON format'),
        ),

    ]
