# Generated by Django 5.2 on 2025-04-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0003_cityconfiguration_config_price_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='lcwaikiki_p_status_77c486_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='lcwaikiki_p_last_ch_a0a67f_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='lcwaikiki_p_product_7c8f60_idx',
        ),
        migrations.RemoveField(
            model_name='config',
            name='default_city',
        ),
        migrations.RemoveField(
            model_name='config',
            name='price_config',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_checking',
        ),
        migrations.RemoveField(
            model_name='product',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='sizestorestock',
            name='original_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
