# Generated by Django 5.2 on 2025-04-11 17:03

from django.db import migrations

class Migration(migrations.Migration):
    """
    This migration is a dummy migration to handle the case where the models
    might already exist in the database from previous migrations.
    """
    dependencies = [
        ('lcwaikiki', '0003_city_product_config_is_active_alter_config_brands_and_more'),
    ]

    operations = [
        # Empty operations to handle the case where the tables already exist
    ]
