# Generated by Django 5.2 on 2025-04-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcwaikiki', '0004_city_product_productsize_store_sizestorestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=35, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('in_stock', models.BooleanField(default=False)),
                ('images', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('size_id', models.CharField(blank=True, max_length=50, null=True)),
                ('size_general_stock', models.IntegerField(default=0)),
                ('product_option_size_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode_list', models.JSONField(default=list)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='lcwaikiki.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'unique_together': {('product', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=200)),
                ('store_county', models.CharField(blank=True, max_length=100, null=True)),
                ('store_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='lcwaikiki.city')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='SizeStoreStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_stocks', to='lcwaikiki.productsize')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_stocks', to='lcwaikiki.store')),
            ],
            options={
                'verbose_name': 'Size Store Stock',
                'verbose_name_plural': 'Size Store Stocks',
                'unique_together': {('product_size', 'store')},
            },
        ),
    ]
